Update deployment.yaml - fix container
stakater/Forecastle pull request #378
Opened 2023-09-06 01:14 UTC by gandazgul

2023-09-14 05:46 UTC, MuneebAijaz requested changes

2023-09-14 05:46 UTC, MuneebAijaz commented on deployments/kubernetes/chart/forecastle/templates/deployment.yaml
> +        securityContext: {{- toYaml .Values.forecastle.container.securityContext | nindent 12 }}
```suggestion
        securityContext: {{- toYaml .Values.forecastle.container.securityContext | nindent 10 }}
```

2023-09-14 05:46 UTC, MuneebAijaz commented on deployments/kubernetes/chart/forecastle/templates/deployment.yaml
> +        {{- toYaml . | nindent 10 }}
```suggestion
        {{- toYaml .Values.forecastle.deployment.securityContext | nindent 8 }}
```

2023-09-14 05:47 UTC, MuneebAijaz commented
hi @gandazgul ive requested some changes, i fear the mistake comes from the old versions of the chart. Please do run helm template to be sure about indentation and templating. thanks

2024-01-17 09:15 UTC, bnallapeta commented
PR is stale. Closing it.

2024-01-17 09:15 UTC, closed without merging

2024-03-21 18:53 UTC, gandazgul commented
Sorry I completely lost track of this I've been using my branch which just works and forgot to check back here. Is the main chart now fixed? At the time this seemed critical the chart was not working at all.